### ISSUE TITLE
Anytype does not support horizontal mode

### ISSUE THREAD

**Issue by codrutpopescu** [anyproto/anytype-kotlin#757] opened 2024-01-08 12:04 UTC
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Rotating a tablet with Anytype open doesn't switch to horizontal mode. 

### Expected Behavior

It should work like a normal app in Desktop mode when used on Android tablets

### Steps To Reproduce

Open Anytpe.
Rotate the tablet

### Environment

```markdown
- OS: Android
- Version: 14
```

**Comment by obvionaoe** [comment] 2024-01-13 22:34
duplicate of #256

**Closed** 2024-01-14 12:11 UTC
Labels: bug
